=== wukw/demo/crawler-analysis/src/main/resources/xml/crawler.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           elementFormDefault="qualified">


    <xs:element name="HttpPages">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:group ref="HttpPageGroup"></xs:group>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:group name="HttpPageGroup">
        <xs:sequence>
            <xs:element ref="HttpPage"></xs:element>
        </xs:sequence>
    </xs:group>

    <xs:element name="HttpPage">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="condition" type="xs:string" minOccurs="0"/>
                <xs:element name="id" type="xs:string"/>
                <xs:element name="needStore" type="xs:boolean" minOccurs="0"/>
                <xs:element name="redirect" type="xs:boolean" minOccurs="0"/>
                <xs:element name="image" type="xs:boolean" minOccurs="0"/>
                <xs:element name="for" type="PageFor" minOccurs="0"/>
                <xs:element name="request" type="HttpPageRequest"/>
                <xs:element name="response" type="HttpPageResponse"/>
                <xs:element name="nextPageId" type="xs:string" minOccurs="0"/>
                <xs:element name="refreshEnabled" type="xs:string" minOccurs="0"/>
                <xs:element name="refreshFromPageId" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="PageFor">
        <xs:attribute name="ketName" type="xs:string"/>
        <xs:attribute name="start" type="xs:int"/>
        <xs:attribute name="end" type="xs:int"/>
        <xs:attribute name="step" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="HttpPageRequest">
        <xs:sequence>
            <xs:element name="url" type="xs:string"/>
            <xs:element name="method" type="xs:string">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="POST||GET"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="body" type="xs:string" minOccurs="0"/>
            <xs:element name="charset" type="xs:string"/>
            <xs:element name="timeout" type="xs:integer"/>
            <xs:element name="headers" type="map" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HttpPageResponse">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="extractors" type="extractors"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="extractors">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="type" type="xs:string" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="JSON||TEXT||HTML"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="element" type="xs:string" minOccurs="0"/>
            <xs:element name="var" type="var" minOccurs="0"/>
            <xs:group ref="stores" minOccurs="0"/>
            <xs:element name="extractors" type="extractors" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="stores">
        <xs:sequence>
            <xs:element name="store" type="stroe"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="stroe">
        <xs:attribute name="element" type="xs:string"/>
        <xs:attribute name="objectName" type="xs:string"/>
        <xs:attribute name="objectField" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="var">
        <xs:attribute name="class"/>
        <xs:attribute name="bean-name"/>
    </xs:complexType>


    <!--map类型-->
    <xs:complexType name="map">
        <xs:sequence>
            <xs:element name="key" type="xs:string"/>
            <xs:element name="value" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== wukw/demo/crawler-analysis/src/main/resources/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<HttpPages
        xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="crawler.xsd">
    <HttpPage>
        <condition>"1=1"</condition>
        <id>login-page</id>
        <needStore>true</needStore>
        <redirect>true</redirect>
        <image>false</image>
        <request>
            <url>https://www.baidu.com/</url>
            <method>GET</method>
            <charset>utf-8</charset>
            <timeout>3000</timeout>
        </request>
        <response>
            <extractors>
                <type>JSON</type>
                <element>user</element>
                <extractors>
                    <type>JSON</type>
                    <store element="id" object-name="user" object-field="user"/>
                </extractors>
                <store/>
            </extractors>
        </response>
    </HttpPage>
    <HttpPage>
        <condition>"1=1"</condition>
        <id>login-page</id>
        <needStore>true</needStore>
        <redirect>true</redirect>
        <image>false</image>
        <request>
            <url>https://www.baidu.com/</url>
            <method>GET</method>
            <charset>utf-8</charset>
            <timeout>3000</timeout>
        </request>
        <response>
            <extractors>
                <type>HTML</type>
                <element>user</element>
                <extractors>
                    <store element="id" object-name="user" object-field="user"/>
                </extractors>
                <store/>
            </extractors>
        </response>
    </HttpPage>

</HttpPages>
